"use client";

import { useState } from "react";
import { PageHead } from "@/components/Shell";
import { Badge, Card, DataTable, Drawer, Empty, ErrorNote, Json, KeyValues, StatCard, StatusBadge, Tabs } from "@/components/ui";
import { brain } from "@/lib/api";
import { useAction, useResource } from "@/lib/hooks";
import { dateTime, inr, inrExact, pct, relativeTime, titleCase, toneFor } from "@/lib/format";

export default function DecisionsPage() {
  const pipeline = useResource(() => brain.pipeline(), []);
  const { busy, error: actionError, message, run } = useAction();
  const [tab, setTab] = useState("current");
  const [openAction, setOpenAction] = useState<any>(null);
  const [openRec, setOpenRec] = useState<any>(null);

  const recommendations: any[] = pipeline.data?.recommendations || [];
  const actions: any[] = pipeline.data?.actions || [];
  const latest = recommendations[0];
  const pending = actions.filter((a) => a.status === "PENDING_APPROVAL");
  const verified = actions.filter((a) => a.status === "VERIFIED");
  const netImpact = actions.reduce((sum, a) => sum + Number(a.outcome?.actual_impact_paise || 0), 0);

  const reload = () => pipeline.reload();

  async function approveRecommendation(rec: any) {
    await run("approve", async () => {
      const created: any = await brain.actOnRecommendation(rec.recommendation_id);
      for (const action of created.actions || []) {
        await brain.approve(action.action_id, action.approval_token);
      }
      await reload();
    }, "Recommendation approved and executed.");
  }

  return (
    <>
      <PageHead
        title="Decisions"
        description="The brain proposes, policy authorises, and the executor only acts after approval. Every step is recorded."
        actions={
          <>
            <button
              className="btn ghost"
              disabled={!!busy}
              onClick={() => run("orch", async () => {
                await brain.orchestrate();
                await reload();
              }, "Re-orchestrated.")}
            >
              {busy === "orch" ? "Orchestrating…" : "Re-orchestrate"}
            </button>
            <button className="btn ghost" disabled={!!busy} onClick={() => run("cycle", async () => {
              await brain.cycle();
              await reload();
            }, "Brain cycle complete.")}>
              {busy === "cycle" ? "Running…" : "Run brain cycle"}
            </button>
          </>
        }
      />
      <ErrorNote>{pipeline.error || actionError}</ErrorNote>
      {message && <p className="notice">{message}</p>}

      <div className="grid g4">
        <StatCard label="Recommendations" value={recommendations.length} foot="Generated by the orchestrator" />
        <StatCard
          label="Awaiting approval"
          value={pending.length}
          tone={pending.length ? "warning" : undefined}
          foot={pending.length ? inr(pending.reduce((s, a) => s + Number(a.amount_paise || 0), 0)) : "Nothing blocked"}
        />
        <StatCard label="Executed & verified" value={verified.length} tone="good" foot={`${actions.length} actions total`} />
        <StatCard label="Net measured impact" value={inr(netImpact)} foot="From the outcome ledger, not the estimate" />
      </div>

      <Tabs
        active={tab}
        onChange={setTab}
        tabs={[
          { id: "current", label: "Recommended action" },
          { id: "approvals", label: "Approvals", count: pending.length },
          { id: "ledger", label: "Action ledger", count: actions.length },
          { id: "history", label: "History", count: recommendations.length },
        ]}
      />

      {tab === "current" &&
        (latest ? (
          <div className="grid split">
            <Card
              title={latest.problem}
              subtitle={`Generated ${relativeTime(latest.created_at)} · ${latest.recommendation_id}`}
              actions={
                <>
                  <StatusBadge value={latest.status} />
                  <Badge tone={toneFor(latest.risk)}>{titleCase(latest.risk)} risk</Badge>
                </>
              }
            >
              <p style={{ fontSize: 13, color: "var(--ink-2)" }}>{latest.why_this}</p>

              <div className="card-title" style={{ margin: "16px 0 6px" }}>
                Proposed actions
              </div>
              {(latest.proposed_action || []).length ? (
                <div className="rowlist">
                  {(latest.proposed_action || []).map((action: any, index: number) => (
                    <div key={index}>
                      <span>
                        <span className="mono">{action.type}</span>
                        {action.reason ? <div className="tiny">{action.reason}</div> : null}
                      </span>
                      <strong className="num">{inr(action.amount ?? action.amount_paise)}</strong>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="tiny">Hold — no action beats doing nothing right now.</p>
              )}

              <div className="card-title" style={{ margin: "16px 0 6px" }}>
                Why not the alternatives?
              </div>
              <div className="rowlist">
                {(latest.alternatives || []).map((alt: any, index: number) => (
                  <div key={`${alt.label}-${index}`} style={{ alignItems: "flex-start" }}>
                    <span>
                      <strong style={{ fontSize: 12.5 }}>{titleCase(alt.label)}</strong>
                      <div className="tiny">{alt.reason}</div>
                    </span>
                    <span className="tiny num" style={{ textAlign: "right", whiteSpace: "nowrap" }}>
                      {inr(alt.projected_cash_paise)}
                      <br />
                      breach {pct(alt.reserve_breach_probability)}
                    </span>
                  </div>
                ))}
              </div>

              <div className="row" style={{ marginTop: 16 }}>
                <button
                  className="btn"
                  disabled={!!busy || !(latest.proposed_action || []).length}
                  onClick={() => approveRecommendation(latest)}
                >
                  {busy === "approve" ? "Executing…" : "Approve & execute"}
                </button>
                <button className="btn ghost" onClick={() => setOpenRec(latest)}>
                  Full record
                </button>
              </div>
            </Card>

            <div className="stack-v">
              <Card title="Evidence the decision rests on" subtitle="Copied from world state at decision time.">
                <KeyValues
                  rows={Object.entries(latest.evidence || {}).map(([key, value]) => [
                    titleCase(key.replace(/_paise$/, "")),
                    key.endsWith("_paise") ? inrExact(Number(value)) : typeof value === "number" ? (value <= 1 ? pct(value) : String(value)) : String(value),
                  ])}
                />
              </Card>
              <Card title="Expected impact" subtitle="Simulated before anything executes.">
                <KeyValues
                  rows={[
                    ["Projected cash", inrExact(latest.expected_impact?.projected_cash_paise)],
                    ["Reserve breach", pct(latest.expected_impact?.reserve_breach_probability)],
                    ["Business impact", inrExact(latest.expected_impact?.business_impact_paise)],
                    ["Confidence", pct(latest.confidence)],
                    ["Simulation", <span className="mono">{latest.simulation_id}</span>],
                  ]}
                />
              </Card>
              <Card title="Agent proposals considered" subtitle="Each agent's bid, with its own confidence.">
                {(latest.proposals || []).length ? (
                  <div className="rowlist">
                    {(latest.proposals || []).map((p: any) => (
                      <div key={p.agent_id} style={{ alignItems: "flex-start" }}>
                        <span>
                          <strong style={{ fontSize: 12.5 }}>{titleCase(p.agent_id)}</strong>
                          <div className="tiny">{p.proposal?.reason}</div>
                        </span>
                        <span className="tiny num" style={{ textAlign: "right", whiteSpace: "nowrap" }}>
                          {inr(p.proposal?.amount_paise)}
                          <br />
                          conf {pct(p.confidence)} · trust {pct(p.trust)}
                        </span>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="tiny">No agent proposed this round.</p>
                )}
              </Card>
            </div>
          </div>
        ) : (
          <Card>
            <Empty title="No recommendation yet" hint="Run a brain cycle or re-orchestrate to generate one." />
          </Card>
        ))}

      {tab === "approvals" && (
        <Card title="Actions awaiting your approval" subtitle="Financial and irreversible actions never execute unattended.">
          {pending.length ? (
            <DataTable
              rows={pending}
              rowKey={(row) => row.action_id}
              onRowClick={setOpenAction}
              columns={[
                { key: "action_type", header: "Action", render: (row) => <span className="mono">{row.action_type}</span> },
                { key: "amount_paise", header: "Amount", align: "right", render: (row) => inrExact(row.amount_paise) },
                { key: "agent_id", header: "Agent", render: (row) => titleCase(row.agent_id) },
                {
                  key: "reason",
                  header: "Why approval is needed",
                  render: (row) => <span className="tiny">{(row.policy_result?.reasons || []).join(" ")}</span>,
                },
                { key: "created_at", header: "Raised", render: (row) => relativeTime(row.created_at) },
                {
                  key: "decide",
                  header: "",
                  align: "right",
                  render: (row) => (
                    <span className="row tight" style={{ justifyContent: "flex-end" }} onClick={(e) => e.stopPropagation()}>
                      <button
                        className="btn xs"
                        disabled={!!busy}
                        onClick={() =>
                          run(`ok-${row.action_id}`, async () => {
                            await brain.approve(row.action_id, row.approval?.token);
                            await reload();
                          }, "Approved and executed.")
                        }
                      >
                        Approve
                      </button>
                      <button
                        className="btn subtle xs"
                        disabled={!!busy}
                        onClick={() =>
                          run(`no-${row.action_id}`, async () => {
                            await brain.reject(row.action_id, row.approval?.token);
                            await reload();
                          }, "Rejected.")
                        }
                      >
                        Reject
                      </button>
                    </span>
                  ),
                },
              ]}
            />
          ) : (
            <Empty title="No approvals pending" hint="Everything the agents proposed was either safe to run or already decided." />
          )}
        </Card>
      )}

      {tab === "ledger" && (
        <Card
          title="Action + outcome ledger"
          subtitle="Predicted impact against the impact actually measured after execution."
        >
          <DataTable
            rows={actions}
            rowKey={(row) => row.action_id}
            onRowClick={setOpenAction}
            columns={[
              { key: "action_type", header: "Action", render: (row) => <span className="mono">{row.action_type}</span> },
              { key: "status", header: "Status", render: (row) => <StatusBadge value={row.status} /> },
              { key: "agent_id", header: "Agent", render: (row) => titleCase(row.agent_id) },
              { key: "amount_paise", header: "Amount", align: "right", render: (row) => inrExact(row.amount_paise) },
              {
                key: "expected",
                header: "Expected",
                align: "right",
                render: (row) => (row.outcome ? inrExact(row.outcome.expected_impact_paise) : "—"),
              },
              {
                key: "actual",
                header: "Actual",
                align: "right",
                render: (row) => (row.outcome ? <strong>{inrExact(row.outcome.actual_impact_paise)}</strong> : "—"),
              },
              {
                key: "error",
                header: "Error",
                align: "right",
                render: (row) =>
                  row.outcome?.prediction_error === null || row.outcome?.prediction_error === undefined
                    ? "—"
                    : pct(row.outcome.prediction_error),
              },
              { key: "created_at", header: "When", render: (row) => dateTime(row.created_at) },
            ]}
          />
        </Card>
      )}

      {tab === "history" && (
        <Card title="Recommendation history" subtitle="Every decision the orchestrator has produced for this merchant.">
          <DataTable
            rows={recommendations}
            rowKey={(row) => row.recommendation_id}
            onRowClick={setOpenRec}
            columns={[
              { key: "problem", header: "Problem" },
              { key: "status", header: "Status", render: (row) => <StatusBadge value={row.status} /> },
              { key: "risk", header: "Risk", render: (row) => <Badge tone={toneFor(row.risk)}>{titleCase(row.risk)}</Badge> },
              { key: "confidence", header: "Confidence", align: "right", render: (row) => pct(row.confidence) },
              {
                key: "actions",
                header: "Actions",
                align: "right",
                render: (row) => (row.actions || []).length,
              },
              { key: "created_at", header: "When", render: (row) => dateTime(row.created_at) },
            ]}
          />
        </Card>
      )}

      <Drawer
        open={!!openAction}
        title={openAction?.action_type || ""}
        subtitle={openAction ? `${openAction.action_id} · ${openAction.status}` : undefined}
        onClose={() => setOpenAction(null)}
      >
        {openAction && (
          <>
            <KeyValues
              rows={[
                ["Status", <StatusBadge value={openAction.status} />],
                ["Agent", titleCase(openAction.agent_id)],
                ["Amount", inrExact(openAction.amount_paise)],
                ["Reversibility", titleCase(openAction.reversibility)],
                ["Rollback", titleCase(openAction.rollback_strategy)],
                ["Requires approval", openAction.requires_approval ? "yes" : "no"],
                ["Reason", openAction.reason || "—"],
                ["Trace", <span className="mono">{openAction.trace_id}</span>],
                ["Created", dateTime(openAction.created_at)],
                ["Executed", openAction.executed_at ? dateTime(openAction.executed_at) : "—"],
              ]}
            />
            {openAction.policy_result && (
              <div>
                <div className="card-title" style={{ marginBottom: 6 }}>
                  Policy decision
                </div>
                <Json value={openAction.policy_result} />
              </div>
            )}
            {openAction.verification && (
              <div>
                <div className="card-title" style={{ marginBottom: 6 }}>
                  Verification
                </div>
                <Json value={openAction.verification} />
              </div>
            )}
            {openAction.outcome && (
              <div>
                <div className="card-title" style={{ marginBottom: 6 }}>
                  Outcome
                </div>
                <Json value={openAction.outcome} />
              </div>
            )}
            <div>
              <div className="card-title" style={{ marginBottom: 6 }}>
                Full record
              </div>
              <Json value={openAction} />
            </div>
          </>
        )}
      </Drawer>

      <Drawer
        open={!!openRec}
        title={openRec?.problem || ""}
        subtitle={openRec?.recommendation_id}
        onClose={() => setOpenRec(null)}
      >
        {openRec && <Json value={openRec} maxHeight={100000} />}
      </Drawer>
    </>
  );
}
